install scripts: trapping ERR to output errors with line numbers

diff --git a/bin/install/debian/install-local b/bin/install/debian/install-local
--- a/bin/install/debian/install-local
+++ b/bin/install/debian/install-local
@@ -1,4 +1,4 @@
-#! /usr/bin/env sh
+#! /usr/bin/env bash
 
 set -e
 
@@ -77,7 +77,21 @@ create_instance_data()
     -n "$NAME" \
     -s "$SERVICE_NAME" \
     -u "$DOMAINS" \
-    -d "$INSTALL_DIR"
+    -d "$INSTALL_DIR" \
+    > /dev/null
+}
+
+error()
+{
+  local parent_lineno="$1"
+  local message="$2"
+  local code="${3:-1}"
+  if [[ -n "$message" ]] ; then
+    echo "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
+  else
+    echo "Error on or near line ${parent_lineno}; exiting with status ${code}"
+  fi
+  exit "${code}"
 }
 
 exit_with_usage_msg()
@@ -135,7 +149,8 @@ install_apps() {
     rapptorcontrolpanel \
     npm run cli -- \
     install \
-    app.93million.plex,app.93million.transmission,app.93million.wg-easy
+    app.93million.plex,app.93million.transmission,app.93million.wg-easy \
+    > /dev/null
 }
 
 install_git()
@@ -166,8 +181,7 @@ pull_docker_images()
   echo -n "Pulling docker images... "
   docker login -u "$DEPLOY_USER" -p "$DEPLOY_PASSWORD" "$DOCKER_REGISTRY" \
     > /dev/null
-  docker compose -f "$COMPOSE_FILE" pull \
-    > /dev/null
+  docker compose -f "$COMPOSE_FILE" pull > /dev/null
   echo "Done"
 }
 
@@ -200,5 +214,7 @@ main()
   install_apps
   restart_app
 }
+
+trap 'error ${LINENO}' ERR
 
 main "$@"
diff --git a/bin/install/debian/install-ssh b/bin/install/debian/install-ssh
--- a/bin/install/debian/install-ssh
+++ b/bin/install/debian/install-ssh
@@ -5,6 +5,18 @@ set -e
 SCRIPT_DIR=$(dirname "$0")
 E_MISSING_ARGS=1
 
+error() {
+  local parent_lineno="$1"
+  local message="$2"
+  local code="${3:-1}"
+  if [[ -n "$message" ]] ; then
+    echo "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
+  else
+    echo "Error on or near line ${parent_lineno}; exiting with status ${code}"
+  fi
+  exit "${code}"
+}
+
 exit_with_usage_msg()
 {
   echo $1
@@ -65,7 +77,7 @@ main()
   cat "$SCRIPT_DIR/install-local" | \
     ssh \
       "$SSH_USER@$HOST" \
-      /usr/bin/env sh /dev/stdin \
+      /usr/bin/env bash /dev/stdin \
       -b "$GIT_BRANCH" \
       -c "$CERTCACHE_CERTBOT_EMAIL" \
       -d "$DOMAINS" \
@@ -75,4 +87,5 @@ main()
       -u "$ACCOUNT_NAME"
 }
 
+trap 'error ${LINENO}' ERR
 main "$@"
